image:
    file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install aider-chat
      pip install open-interpreter
    command: |
          aider -h
          ctags --version
          interpreter --version


